<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Configurations>Development;Staging;Production</Configurations>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Data\**" />
	  <Content Remove="Data\**" />
	  <EmbeddedResource Remove="Data\**" />
	  <None Remove="Data\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="AddProductStockScript.cs" />
	  <Compile Remove="BaseDatabaseScript.cs" />
	  <Compile Remove="DatabaseManager.cs" />
	  <Compile Remove="DatabaseManagerExtension.cs" />
	  <Compile Remove="DatabaseVersion.cs" />
	  <Compile Remove="IDatabaseManager.cs" />
	  <Compile Remove="IDatabaseScript.cs" />
	  <Compile Remove="InitialSchemaScript.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.7.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\noware\Noware.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Settings\appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Settings\appsettings.*.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
