// <auto-generated>

/*
Everyware - Copyright © 2025 by CLS

********************************************************************************************************************************************
****
**** Project:           Elseware
****
**** Module:            001_CreateDatabase - Migration
****
**** Version:           2025.1.0.0001
****
**** Created By:        Cristiano Luelli
**** Created On:        30/08/2025
****
**** Last Changed By:   Cristiano Luelli
**** Last Changed On:   30/08/2025
****
********************************************************************************************************************************************

Everyware - Copyright © 2025 by CLS
*/

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Elseware.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class _001_CreateDatabase : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Account",
                columns: table => new
                {
                    KEY_Account = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    DTE_Birth = table.Column<DateTime>(type: "datetime", nullable: true),
                    TXT_FirstName = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true),
                    TXT_Surname = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true),
                    IDN_Account = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    TXT_NormalizedUserName = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    TXT_Email = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    TXT_NormalizedEmail = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    BLN_EmailConfirmed = table.Column<bool>(type: "bit", nullable: false),
                    TXT_PasswordHash = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TXT_SecurityStamp = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TXT_ConcurrencyStamp = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TXT_PhoneNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BLN_PhoneNumberConfirmed = table.Column<bool>(type: "bit", nullable: false),
                    BLN_TwoFactorEnabled = table.Column<bool>(type: "bit", nullable: false),
                    DTE_LockoutEnd = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    BLN_LockoutEnabled = table.Column<bool>(type: "bit", nullable: false),
                    INT_AccessFailedCount = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Account", x => x.KEY_Account);
                });

            migrationBuilder.CreateTable(
                name: "Role",
                columns: table => new
                {
                    KEY_Role = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IDN_Role = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    TXT_NormalizedName = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    TXT_ConcurrencyStamp = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Role", x => x.KEY_Role);
                });

            migrationBuilder.CreateTable(
                name: "AccountClaim",
                columns: table => new
                {
                    INT_Claim = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    LNK_Account = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    TXT_ClaimType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TXT_ClaimValue = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AccountClaim", x => x.INT_Claim);
                    table.ForeignKey(
                        name: "FK_AccountClaim_Account_LNK_Account",
                        column: x => x.LNK_Account,
                        principalTable: "Account",
                        principalColumn: "KEY_Account",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AccountLogin",
                columns: table => new
                {
                    TXT_Provider = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    TXT_Key = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    TXT_DisplayName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LNK_Account = table.Column<Guid>(type: "uniqueidentifier", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AccountLogin", x => new { x.TXT_Provider, x.TXT_Key });
                    table.ForeignKey(
                        name: "FK_AccountLogin_Account_LNK_Account",
                        column: x => x.LNK_Account,
                        principalTable: "Account",
                        principalColumn: "KEY_Account",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AccountToken",
                columns: table => new
                {
                    LNK_Account = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    TXT_LoginProvider = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    TXT_TokenName = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    TXT_TokenValue = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AccountToken", x => new { x.LNK_Account, x.TXT_LoginProvider, x.TXT_TokenName });
                    table.ForeignKey(
                        name: "FK_AccountToken_Account_LNK_Account",
                        column: x => x.LNK_Account,
                        principalTable: "Account",
                        principalColumn: "KEY_Account",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AccountRole",
                columns: table => new
                {
                    LNK_Account = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    LNK_Role = table.Column<Guid>(type: "uniqueidentifier", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AccountRole", x => new { x.LNK_Account, x.LNK_Role });
                    table.ForeignKey(
                        name: "FK_AccountRole_Account_LNK_Account",
                        column: x => x.LNK_Account,
                        principalTable: "Account",
                        principalColumn: "KEY_Account",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AccountRole_Role_LNK_Role",
                        column: x => x.LNK_Role,
                        principalTable: "Role",
                        principalColumn: "KEY_Role",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "RoleClaim",
                columns: table => new
                {
                    INT_Claim = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    LNK_Role = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    TXT_ClaimType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TXT_ClaimValue = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RoleClaim", x => x.INT_Claim);
                    table.ForeignKey(
                        name: "FK_RoleClaim_Role_LNK_Role",
                        column: x => x.LNK_Role,
                        principalTable: "Role",
                        principalColumn: "KEY_Role",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "EmailIndex",
                table: "Account",
                column: "TXT_NormalizedEmail");

            migrationBuilder.CreateIndex(
                name: "UserNameIndex",
                table: "Account",
                column: "TXT_NormalizedUserName",
                unique: true,
                filter: "[TXT_NormalizedUserName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_AccountClaim_LNK_Account",
                table: "AccountClaim",
                column: "LNK_Account");

            migrationBuilder.CreateIndex(
                name: "IX_AccountLogin_LNK_Account",
                table: "AccountLogin",
                column: "LNK_Account");

            migrationBuilder.CreateIndex(
                name: "IX_AccountRole_LNK_Role",
                table: "AccountRole",
                column: "LNK_Role");

            migrationBuilder.CreateIndex(
                name: "RoleNameIndex",
                table: "Role",
                column: "TXT_NormalizedName",
                unique: true,
                filter: "[TXT_NormalizedName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_RoleClaim_LNK_Role",
                table: "RoleClaim",
                column: "LNK_Role");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AccountClaim");

            migrationBuilder.DropTable(
                name: "AccountLogin");

            migrationBuilder.DropTable(
                name: "AccountRole");

            migrationBuilder.DropTable(
                name: "AccountToken");

            migrationBuilder.DropTable(
                name: "RoleClaim");

            migrationBuilder.DropTable(
                name: "Account");

            migrationBuilder.DropTable(
                name: "Role");
        }
    }
}
